### ISSUE TITLE
some fetuchers cant able to show in landscape mode

### ISSUE THREAD

**Issue by rizwankhan003** [samsumas/LivingBurger#7]
#### Expected behavior
user should be able to see whole page in landscape mode .

#### Actual behavior
when i rotated my phone from portrait to landscape some features cant able to watch in BurgerWP home page .

#### How to reproduce
* Download the app
* Open it then you must be in pattern page
* Then click back button to home page
* Then rotated your phone from portrait to landscape
* Note the bug
---
Browser: BurgerWP V1.0
Operating system: Android version 7.0
Device: HUAWEI Mate 10 lite

#### Recording Of The Bug
https://www.youtube.com/watch?v=t17abcjVtO0

**Comment by samsumas** [comment]
Thanks for pointing this out, i didnt saw it ^^'
I added scrollbars in 28138b7ad74875e1dc3827d413df96ea16eb0934 so it should be fixed in the next release :)
